name: publish to ghcr
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  push:
    name: "g5v:latest"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}
      - uses: actions/checkout@v2.5.0
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: DockerfileLight
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/g5v:latest
